[package]
name = "poker-parser"
version.workspace = true
edition.workspace = true

[dependencies]
braid-engine = { path = "../braid-engine" }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
regex = "1.10"
lazy_static = "1.4"
chrono = "0.4"
